services:
  - type: web
    name: vestro
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RANDOM_ORG_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 